"""create activities, categories, photos, and activities_categories tables

Revision ID: afd99b30b7fe
Revises: b35d487a07cb
Create Date: 2023-08-17 22:07:57.609526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afd99b30b7fe'
down_revision: Union[str, None] = 'b35d487a07cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('weather', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_category_association',
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_activity_category_association_activity_id_activities')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_activity_category_association_category_id_categories'))
    )
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_description', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_photos_activity_id_activities')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    op.drop_table('activity_category_association')
    op.drop_table('categories')
    op.drop_table('activities')
    # ### end Alembic commands ###
